<?php

$GLOBALS['__cfg'] = array(
    'database' => array(
        // 'driver' => '',
        'host' => 'localhost',
        'username' => 'pweasel',
        'password' => 'pweasel',
        'database' => 'pweasel',
        )
    );
// autogenerated /etc/schema.php
$GLOBALS['__cfg']['localhost']['pweasel']['user'] = array (
    'id' =>
    array (
        'Field' => 'id',
        'Type' => 'int(10) unsigned',
        'Null' => 'NO',
        'Key' => 'PRI',
        'Default' => '0',
        'Extra' => '',
        ),
    'name' =>
    array (
        'Field' => 'name',
        'Type' => 'varchar(50)',
        'Null' => 'YES',
        'Key' => '',
        'Default' => NULL,
        'Extra' => '',
        ),
    );


